.TH "form.h" 3 "Sun Jan 15 2017" "Version 2.1.0" "TenTen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
form.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPoint\fP"
.br
.RI "\fBPoint\fP structure\&. "
.ti -1c
.RI "class \fBForm\fP"
.br
.RI "\fBForm\fP class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORM_DEFAULT_SIZE\fP   5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FORM_DEFAULT_SIZE   5"

.PP
Definition at line 31 of file form\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TenTen from the source code\&.
