.TH "Form" 3 "Sun Jan 15 2017" "Version 2.1.0" "TenTen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Form \- \fBForm\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <form\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBForm\fP (const \fBForm\fP &_form)"
.br
.RI "Constructor by copying\&. "
.ti -1c
.RI "\fB~Form\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBForm\fP & \fBoperator=\fP (const \fBForm\fP &_form)"
.br
.RI "Overload of affectation operator\&. "
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "Clear the form\&. "
.ti -1c
.RI "void \fBadd\fP (\fBPoint\fP _coor)"
.br
.RI "Add a square\&. "
.ti -1c
.RI "void \fBadd\fP (int _x, int _y)"
.br
.RI "Add a square\&. "
.ti -1c
.RI "size_t \fBgetsize\fP () const"
.br
.RI "Accesor to the form's size\&. "
.ti -1c
.RI "\fBPoint\fP \fBoperator[]\fP (size_t) const"
.br
.RI "Accesor to a specific square\&. "
.ti -1c
.RI "\fBPoint\fP \fBgetboxmin\fP () const"
.br
.RI "Accesor to the minimal bounding box\&. "
.ti -1c
.RI "\fBPoint\fP \fBgetboxmax\fP () const"
.br
.RI "Accesor to the maximal bounding box\&. "
.ti -1c
.RI "std::string \fBwrite\fP () const"
.br
.RI "\fBForm\fP's display\&. "
.ti -1c
.RI "void \fBread\fP (const std::string &)"
.br
.RI "\fBForm\fP reading\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBForm\fP class\&. 

Considers forms as squares's group with a bounding box\&. 
.PP
Definition at line 39 of file form\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Form::Form ()"

.PP
Default constructor\&. Create an empty shape\&. 
.PP
Definition at line 8 of file form\&.cpp\&.
.SS "Form::Form (const \fBForm\fP & _form)"

.PP
Constructor by copying\&. Create a form which is the perfect copy of another\&.
.PP
\fBParameters:\fP
.RS 4
\fI_form\fP : The form to copy\&. 
.RE
.PP

.PP
Definition at line 19 of file form\&.cpp\&.
.SS "Form::~Form ()"

.PP
Destructor\&. 
.PP
Definition at line 32 of file form\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Form::add (\fBPoint\fP _coor)"

.PP
Add a square\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_coor\fP : New square location 
.RE
.PP

.PP
Definition at line 68 of file form\&.cpp\&.
.SS "void Form::add (int _x, int _y)"

.PP
Add a square\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_x\fP : New square's X location 
.br
\fI_y\fP : New square's Y location 
.RE
.PP

.PP
Definition at line 73 of file form\&.cpp\&.
.SS "void Form::clear ()"

.PP
Clear the form\&. Set form's values as they'll be if the form was just created\&. 
.PP
Definition at line 59 of file form\&.cpp\&.
.SS "\fBPoint\fP Form::getboxmax () const"

.PP
Accesor to the maximal bounding box\&. 
.PP
\fBReturns:\fP
.RS 4
The maximal bounding box 
.RE
.PP

.PP
Definition at line 108 of file form\&.cpp\&.
.SS "\fBPoint\fP Form::getboxmin () const"

.PP
Accesor to the minimal bounding box\&. 
.PP
\fBReturns:\fP
.RS 4
The minimal bounding box 
.RE
.PP

.PP
Definition at line 103 of file form\&.cpp\&.
.SS "size_t Form::getsize () const"

.PP
Accesor to the form's size\&. 
.PP
\fBReturns:\fP
.RS 4
The size 
.RE
.PP

.PP
Definition at line 93 of file form\&.cpp\&.
.SS "\fBForm\fP & Form::operator= (const \fBForm\fP & _form)"

.PP
Overload of affectation operator\&. Change the form radicaly\&.
.PP
\fBParameters:\fP
.RS 4
\fI_form\fP : The form to take
.RE
.PP
\fBReturns:\fP
.RS 4
The new form 
.RE
.PP

.PP
Definition at line 38 of file form\&.cpp\&.
.SS "\fBPoint\fP Form::operator[] (size_t n) const"

.PP
Accesor to a specific square\&. 
.PP
\fBReturns:\fP
.RS 4
the square location 
.RE
.PP

.PP
Definition at line 98 of file form\&.cpp\&.
.SS "void Form::read (const std::string & str)"

.PP
\fBForm\fP reading\&. Read a string that save form's values\&. 
.PP
Definition at line 124 of file form\&.cpp\&.
.SS "std::string Form::write () const"

.PP
\fBForm\fP's display\&. 
.PP
\fBReturns:\fP
.RS 4
Corresponding string 
.RE
.PP

.PP
Definition at line 114 of file form\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TenTen from the source code\&.
