.TH "main.cpp" 3 "Sun Jan 15 2017" "Version 2.1.0" "TenTen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'includeGUI\&.h'\fP
.br
\fC#include 'color\&.h'\fP
.br
\fC#include 'global_log\&.h'\fP
.br
\fC#include 'option\&.h'\fP
.br
\fC#include <ncurses\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLOBAL_LOG_FILE\fP   'log\&.txt'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBncurses_init\fP ()"
.br
.ti -1c
.RI "void \fBncurses_init_mouse\fP ()"
.br
.ti -1c
.RI "void \fBncurses_quit\fP ()"
.br
.ti -1c
.RI "void \fBncurses_terminate\fP ()"
.br
.ti -1c
.RI "void \fBdisplay_help\fP ()"
.br
.ti -1c
.RI "void \fBdisplay_version\fP ()"
.br
.ti -1c
.RI "void \fBdisplay_authors\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLOBAL_LOG_FILE   'log\&.txt'"

.PP
Definition at line 15 of file main\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void display_authors ()"

.PP
Definition at line 102 of file main\&.cpp\&.
.SS "void display_help ()"

.PP
Definition at line 75 of file main\&.cpp\&.
.SS "void display_version ()"

.PP
Definition at line 96 of file main\&.cpp\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 109 of file main\&.cpp\&.
.SS "void ncurses_init ()"

.PP
Definition at line 28 of file main\&.cpp\&.
.SS "void ncurses_init_mouse ()"

.PP
Definition at line 50 of file main\&.cpp\&.
.SS "void ncurses_quit ()"

.PP
Definition at line 56 of file main\&.cpp\&.
.SS "void ncurses_terminate ()"

.PP
Definition at line 64 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TenTen from the source code\&.
